#配置端口
server:
  port: 8080

#spring配置
spring:
  #配置模板缓存
  thymeleaf:
    cache: false
  #配置上传的最大文件限制
  servlet:
    multipart:
      max-file-size: 10MB

#dubbo消费者配置
dubbo:
  application:
    name: shop_back
  registry:
    address: zookeeper://47.112.22.169:2181

#配置FastDFS文件上传下载
fdfs:
  #搜索链追踪器端口
  tracker-list: 47.112.22.169:22122
  #上传的缩略图尺寸
  thumb-image:
    width: 100
    height: 100
  pool:
    jmx-enabled: false
    #自定义商品图片路径前缀
  goodsImgPath: http://47.112.22.169/